(define (* b n)
    (mul-iter b n 0))

(define (mul-iter b n a)
    (cond ((= n 0)
            a)
          ((even? n)
            (mul-iter (double b)
                       (halve n)
                       a))
          ((odd? n)
            (mul-iter b
                       (- n 1)
                       (+ b a)))))
(define (double x)
  (+ x x))
(define (halve x)
  (/ x 2))